# Logging properties
# Let's have a dedicated log file for each profile because it's more demonstrative (exactly what we need in sample project)
logging.file.name=logs/datetime-service-env-local.log
logging.pattern.file=%date{YYYY-MM-dd HH:mm:ss.SSS} *%-5level* [%thread] |%logger| %msg%n
logging.pattern.console=%date{YYYY-MM-dd HH:mm:ss.SSS} *%-5level* [%thread] |%logger| %msg%n
logging.include-application-name=false
logging.level.root=info
logging.level.web=debug
logging.level.ua.od.whcrow.samples.spring.cloud.service.datetime=debug
