# Logging properties
logging.file.name=logs/default.log
logging.pattern.file=%date{YYYY-MM-dd HH:mm:ss.SSS} *%-5level* [%thread] |%logger| %msg%n
logging.pattern.console=%date{YYYY-MM-dd HH:mm:ss.SSS} *%-5level* [%thread] |%logger| %msg%n
logging.include-application-name=false
logging.level.root=info
logging.level.web=debug
logging.level.ua.od.whcrow.samples.spring.cloud.service.datetime=debug
