# Logging properties
logging.file.name=logs/default.log
# Use Elastic Common Schema log format
# https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.structured
logging.structured.format.file=ecs
# The only way to disable console logging without locking yourself on logging solution
logging.pattern.console=
logging.level.root=info
logging.level.ua.od.whcrow.samples.spring.cloud.service.datetime=info
