# Logging properties
logging.file.name=logs/default.log
# Use Elastic Common Schema log format
# https://docs.spring.io/spring-boot/reference/features/logging.html#features.logging.structured
logging.structured.format.file=ecs
logging.threshold.console=off
logging.level.root=info
logging.level.ua.od.whcrow.samples.spring.cloud.service.datetime=info
